[package]
name = "tarot"
version = "1.0.0"
upgrade_policy = "compatible"

[addresses]
std = "0x1"
admin = "<0xaddress>"
treasury = "<0xaddress>"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "testnet" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token-objects", rev = "testnet" }
